# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Battleship' do
	pod 'pop', '~> 1.0'
	pod 'Shimmer', '~> 1.0.1'
	pod 'BPForms'
	pod 'SIAlertView'
	pod 'SVProgressHUD', :head
end

target 'BattleshipTests' do

end

